-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES from USED_GOODS_BOARD B 
join USED_GOODS_USER U on b.WRITER_ID=u.USER_ID 
where b.status='DONE' GROUP BY U.USER_ID HAVING TOTAL_SALES>=700000 ORDER BY TOTAL_SALES;